[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "lumache"
authors = [{name = "NGINX", email = "g.chow@f5"}]
dynamic = ["version", "description"]
